from typing import List, Dict, Any
import datetime

def format_timestamp(seconds: float, fmt: str = "srt") -> str:
    """
    格式化时间戳。
    SRT: HH:MM:SS,mmm
    VTT: HH:MM:SS.mmm
    ASS: H:MM:SS.cc
    """
    td = datetime.timedelta(seconds=seconds)
    total_seconds = int(td.total_seconds())
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    secs = total_seconds % 60
    millis = int((seconds - total_seconds) * 1000)

    if fmt == "srt":
        return f"{hours:02}:{minutes:02}:{secs:02},{millis:03}"
    elif fmt == "vtt":
        return f"{hours:02}:{minutes:02}:{secs:02}.{millis:03}"
    elif fmt == "ass":
        centis = millis // 10
        return f"{hours}:{minutes:02}:{secs:02}.{centis:02}"
    return str(seconds)

def export_srt(segments: List[Dict[str, Any]]) -> str:
    """
    生成 SRT 格式字幕。
    """
    output = []
    for i, seg in enumerate(segments):
        start = format_timestamp(seg["start"], "srt")
        end = format_timestamp(seg["end"], "srt")
        text = seg["text"]
        output.append(f"{i+1}\n{start} --> {end}\n{text}\n")
    return "\n".join(output)

def export_vtt(segments: List[Dict[str, Any]]) -> str:
    """
    生成 WebVTT 格式字幕。
    """
    output = ["WEBVTT\n"]
    for i, seg in enumerate(segments):
        start = format_timestamp(seg["start"], "vtt")
        end = format_timestamp(seg["end"], "vtt")
        text = seg["text"]
        output.append(f"{start} --> {end}\n{text}\n")
    return "\n".join(output)

def export_ass(segments: List[Dict[str, Any]], title="LiveCaptions") -> str:
    """
    生成 ASS 格式字幕 (包含基本样式)。
    """
    header = f"""[Script Info]
; Script generated by LiveCaptions
Title: {title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    output = [header]
    for seg in segments:
        start = format_timestamp(seg["start"], "ass")
        end = format_timestamp(seg["end"], "ass")
        text = seg["text"].replace("\n", "\\N")
        output.append(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{text}")
    return "\n".join(output)
